### PR TITLE
matrix: add project homeserver

### PR DESCRIPTION
**Pull request by nixbitcoin**
We should be self-reliant for our communication infrastructure. This matrix homeserver configuration is running live on [synapse.nixbitcoin.org](https://synapse.nixbitcoin.org) and reachable on [Tor](http://outwtosg7hmgmeivjwbhxryp7vjwzxu3ebg24myaaupluwioxeqchmqd.onion). Please review. Message me if you want an account.

### CODE REVIEW

**Comment by jonasnick** [comment]
concept ACK. I like where matrix is headed. I did not find a client yet that's lightweight, not very hard to use and supports end to end encryption. I'm using Elements right now which ticks the latter two boxes. Should this PR also change the website to mention that this exists?

**Comment by nixbitcoin** [comment]
Registrations opened with email verification.

> Should this PR also change the website to mention that this exists?

Done

**Comment by nixbitcoin** [comment]
Took out the default message deletion after a week, caused a lot of issues. You can still set custom message retention periods with state events as described here https://brendan.abolivier.bzh/matrix-retention-policies/ & here https://github.com/matrix-org/synapse/blob/develop/docs/message_retention_policies.md

**Comment by erikarvstedt** [comment]
[Fixups](https://github.com/erikarvstedt/nixbitcoin.org/commits/matrix-ea).

Commits `fixup! improve formatting` to `fixup! add header comment` (inclusive) are non-functional and have no effect on the system derivation.
You can test this by evaluating the system (within `nix-shell`):
```
scenarioOverridesFile=$(realpath scenarios.nix) nix-instantiate --eval -E "($(run-node -s nixbitcoinorg-non-hardened vmTestNixExpr)).outPath"
```

**Comment by nixbitcoin** [comment]
Merged your fixes

**Comment by erikarvstedt** [comment]
ACK 77106e58ba5485cfb1ce1365fb323679ba82a910

**Review by erikarvstedt — APPROVED** [review]
ACK 77106e58ba5485cfb1ce1365fb323679ba82a910

**Pull request merged**
